@startuml

skinparam Linetype ortho


[Restaurant\nManagement \nSystem Server] as RMS

database "Staff Database" as SD {
  [Waiters Info]
  [Chef Info]
}

database "Customer Database" as CD {
   [Membership Customer]
   [New Customer]
}

package "Utilities"{
    Component "Data Processing"
}

package "User Interface" as UI{
    [WebApplication]
}

package "Report Generation" {
    [Report]
}

cloud "Payment Gateway"{
    Component "Payment Report" as PR
}

RMS ..> Utilities : <<Resides>>
RMS -(0- CD : File Transfer Protocol
RMS -(0- SD : File Transfer Protocol
UI -(0- RMS : <<HTTP>>
Report -(0-  RMS : <<use>>
Report -left-> PR : <<uses>>

@enduml
