@startuml Sequenc2

skinparam Style strictuml
skinparam SequenceMessageAlignment center

"Customer" ->> "Reservation System" : makes reservation

Customer ->> "Reservation System" : change table

"Reservation System" ->> "Reservation System" : Check if possible

"Reservation System" ->> Customer : Table Changed

Customer ->> "Waiter" : Request Menu

"Waiter" ->> Customer : Provide Menu

Customer ->> Customer : Browse Menu

Customer ->> "Waiter" : Place order

"Waiter" ->> "Order System" : Update Order

Customer ->> "Waiter" : Make a Special Request in the order

"Waiter" ->> "Order System" : Update Order


"Waiter" ->> Customer : Special Request Confirmed


"Order System" ->> Kitchenstaff : Provide Order Details

Kitchenstaff ->> Kitchenstaff :Prepare Order

Kitchenstaff ->> "Order System" : Update order

"Order System" ->> Waiter : Order to Deliver

Waiter ->> Customer : Deliver Food

Customer ->> Customer : Eat Food

Customer ->> "Waiter" : Make Payment

Waiter ->> "Order System" : Update Order

Customer ->> Waiter :"Give tip"



@enduml
